name: Runtime tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  syntax:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 3.1
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.1.x
    - name: Loading all files should not crash
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        ./scripts/require_all.sh
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 3.1
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.1.x
    - name: Run rspec tests
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rspec