name: Integration tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  connect-to-server:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 3.1
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.1.x
    - name: Prepare
      run: |
        sudo apt-get update -y
        sudo apt-get install -y shellcheck teeworlds teeworlds-server
        gem install bundler
        gem install rubocop:1.31.2
        bundle install --jobs 4 --retry 3
    - name: Test sending chat messages
      run: |
        ./integration_test/run.sh client/chat.rb
    - name: Test reconnect
      run: |
        ./integration_test/run.sh client/reconnect.rb
    - name: Test rcon
      run: |
        ./integration_test/run.sh client/rcon.rb