name: Integration tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  connect-to-server:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 3.1
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.1.x
    - name: Prepare
      run: |
        sudo apt-get update -y
        sudo apt-get install -y shellcheck teeworlds-server
        gem install bundler
        gem install rubocop:1.31.2
        bundle install --jobs 4 --retry 3
        wget https://github.com/ChillerDragon/teeworlds/releases/download/v0.7.5-headless/teeworlds-0.7.5-linux_x86_64.tar.gz
        tar -xvzf teeworlds-0.7.5-linux_x86_64.tar.gz
        sudo mkdir -p /usr/local/bin/
        sudo mv teeworlds-0.7.5-linux_x86_64/teeworlds /usr/local/bin/teeworlds-headless
        rm -rf teeworlds-0.7.5-linux_x86_64*
        wget https://github.com/ChillerDragon/ddnet/releases/download/v16.5-headless/DDNet-headless.zip
        unzip DDNet-headless.zip
        sudo mv DDNet-headless /usr/local/bin
        rm DDNet-headless.zip
    - name: Test sending chat messages
      run: |
        ./integration_test/run.sh client/chat.rb
    - name: Test reconnect
      run: |
        ./integration_test/run.sh client/reconnect.rb
    - name: Test rcon
      run: |
        ./integration_test/run.sh client/rcon.rb